require("basic")
require("plugins")
-- require('keymaps')
require("theme")
-- require('plugin/vim-go')
-- require('plugin/ale')
-- require('plugin/coc')
require("plugin/notify").setup()
require("plugin/airline")
require("plugin/nvim-tree")
require("plugin/telescope")
-- require('keymaps')
require("lsp/setup")
require("lsp/ui")
require("plugin/cmp")
require("plugin/outline")
require("plugin/gitsigns")
require("autocmd")
require("dap/nvim-dap")
require("plugin.nvim-treesitter")
require("lsp.null-ls")
-- require("lsp.formatter")
